name: Publish Docker Image


on:
  pull_request:
    branches:
      - 'temp'

env:
  # TODO: Change variable to your image's name.
  IMAGE: github-k8s-runner
  GITHUB_SHA: ${{ github.sha }}

jobs:
  trivy-scan:
    # Ensure lintAllTheThings job passes before pushing image.
    # needs: lintAllTheThings

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      # - name: Build image
      #   run: docker build -t "us.gcr.io/ebo-sandbox/$IMAGE:${GITHUB_SHA:0:8}" .

      - name: Run Trivy scan to check container image for vulnerabilities
        uses: ebomart/build-publish-docker@main
        with:
          registry_host: us.gcr.io
          gke_project: ebo-sandbox
          image_name: $IMAGE
          google_private_key: ${{ secrets.GOOGLE_PRIVATE_KEY_SANDBOX }}
          sha: ${GITHUB_SHA:0:8}
          file: Dockerfile
        # publish-image:
  #   runs-on: ubuntu-latest
  #   needs: trivy-scan
  #   steps:
  #     - uses: google-github-actions/setup-gcloud@master
  #       with:
  #         project_id: ${{ secrets.GCP_PROJECT_ID_SANDBOX }}
  #         service_account_key: ${{ secrets.GOOGLE_PRIVATE_KEY_SANDBOX }}
  #         export_default_credentials: true

  #     - run: |
  #         gcloud auth configure-docker

  #     - name: Publish
  #       run: |
  #         docker push us.gcr.io/ebo-sandbox/$IMAGE:${GITHUB_SHA:0:8}

